"""empty message

Revision ID: 193021d83c5f
Revises: 
Create Date: 2023-06-02 13:03:30.163088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193021d83c5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID rкомментария.'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
