"""empty message

Revision ID: 70ff64ffed21
Revises: 193021d83c5f
Create Date: 2023-06-09 13:50:28.529708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ff64ffed21'
down_revision = '193021d83c5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID пользователя'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Username пользователя (Только английские буквы и цифры)'),
    sa.Column('password', sa.Text(), nullable=False, comment='Хэш пароля'),
    sa.Column('registred_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Время регистрации пользователя.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Флаг активен ли пользователь.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='ID rкомментария.'),
    sa.PrimaryKeyConstraint('id', name='orders_pkey')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
